import { StyleSheet, Platform } from 'react-native';

export const colors = {
  primary: '#3B82F6',
  primaryDark: '#2563EB',
  danger: '#EF4444',
  success: '#10B981',
  background: '#F5F7FB',
  surface: '#ffffff',
  textMain: '#0F172A',
  textSecondary: '#64748B',
  border: '#E2E8F0',
  muted: '#94A3B8',
  track: '#E5EAF2',
};

export const globalStyles = StyleSheet.create({
  // Layout
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
  },
  
  // Header & Progress
  headerContainer: { marginBottom: 22 },
  counterText: { fontSize: 34, fontWeight: '800', textAlign: 'center', marginBottom: 10, color: colors.textMain, letterSpacing: 0.3 },
  progressTrack: { height: 12, backgroundColor: colors.track, borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999 },
  macroTargetsRow: { marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  macroTargetText: { fontSize: 12, color: colors.textSecondary, fontWeight: '700' },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 4,
    marginBottom: 12,
  },
  tabButton: {
    flex: 1,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  activeTabButton: {
    backgroundColor: colors.primary,
  },
  tabButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  activeTabButtonText: {
    color: colors.surface,
  },

  // Date Switcher
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  dateText: { fontSize: 15, fontWeight: '700', color: colors.textMain },
  arrowButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary + '14',
  },
  arrow: { fontSize: 18, color: colors.primaryDark, fontWeight: '700' },

  // Forms & Inputs
  card: {
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
      },
      android: { elevation: 3 },
    }),
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    fontSize: 15,
    color: colors.textMain,
    backgroundColor: '#FBFDFF',
  },
  button: { backgroundColor: colors.primary, paddingVertical: 13, borderRadius: 10, alignItems: 'center', marginTop: 6 },
  buttonText: { color: colors.surface, fontWeight: '700', fontSize: 15 },
  secondaryButton: {
    backgroundColor: colors.primary + '18',
    borderRadius: 10,
    paddingHorizontal: 12,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primary + '33',
  },
  secondaryButtonWide: {
    backgroundColor: colors.primary + '12',
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primary + '30',
    marginBottom: 10,
  },
  secondaryButtonText: { color: colors.primaryDark, fontWeight: '700', fontSize: 13 },
  sectionTitle: { fontSize: 13, fontWeight: '700', color: colors.textSecondary, marginBottom: 8, textTransform: 'uppercase' },
  lookupRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  lookupSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: '#FBFDFF',
    paddingHorizontal: 10,
    marginBottom: 6,
  },
  searchIcon: { color: colors.muted, fontSize: 16, fontWeight: '700' },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.textMain,
    paddingVertical: 11,
  },
  clearSearchText: { color: colors.primaryDark, fontSize: 12, fontWeight: '700' },
  lookupHint: { color: colors.muted, fontSize: 12, marginBottom: 10, marginTop: 2 },
  lookupInput: { flex: 1 },
  inputRow: { flexDirection: 'row', gap: 8 },
  macroInput: { flex: 1 },
  scannerWrap: { borderRadius: 12, overflow: 'hidden', marginBottom: 10, borderWidth: 1, borderColor: colors.border },
  scanner: { height: 220, width: '100%' },
  searchResults: { maxHeight: 180, marginBottom: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 10 },
  searchResultItem: { paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
  searchResultTitle: { color: colors.textMain, fontWeight: '600', fontSize: 14 },
  searchResultSub: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    maxHeight: '80%',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOpacity: 0.15,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
      },
      android: { elevation: 6 },
    }),
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#F8FAFF',
  },
  modalTitle: { color: colors.textMain, fontSize: 16, fontWeight: '700' },
  modalSubtitle: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
  modalCloseButton: {
    backgroundColor: colors.primary + '14',
    borderWidth: 1,
    borderColor: colors.primary + '33',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  modalCloseButtonText: { color: colors.primaryDark, fontSize: 12, fontWeight: '700' },
  modalResultsList: { padding: 10, maxHeight: 420 },
  modalResultCard: { paddingVertical: 8, paddingHorizontal: 8, borderRadius: 10, backgroundColor: '#FCFDFF' },
  modalResultTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  modalItemSeparator: { height: 8 },
  modalStateWrap: { padding: 16, alignItems: 'center' },
  kcalPill: {
    backgroundColor: colors.success + '1A',
    borderColor: colors.success + '3A',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  kcalPillText: { color: colors.success, fontSize: 11, fontWeight: '700' },

  // List Items
  listItem: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    padding: 14, 
    backgroundColor: colors.surface, 
    borderRadius: 14, 
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  itemName: { fontSize: 16, fontWeight: '700', color: colors.textMain },
  itemSubtext: { color: colors.textSecondary, marginTop: 2 },
  deleteText: { color: colors.danger, fontWeight: '700' },
  completeText: { color: colors.success, fontWeight: '700' },
  emptyText: { textAlign: 'center', marginTop: 24, color: colors.muted, fontSize: 14, fontWeight: '600' },
  inlineEmptyText: { textAlign: 'center', color: colors.muted, fontSize: 13, paddingVertical: 6 },
  exerciseActions: { alignItems: 'flex-end', justifyContent: 'space-between', minHeight: 46 },
  todoPill: {
    color: colors.primaryDark,
    marginTop: 6,
    fontSize: 12,
    fontWeight: '700',
  },
  donePill: {
    color: colors.success,
    marginTop: 6,
    fontSize: 12,
    fontWeight: '700',
  },

  // Settings Panel
  settingsToggle: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  settingsToggleText: { color: colors.textMain, fontWeight: '700', fontSize: 14 },
  settingsPanel: { backgroundColor: colors.surface, padding: 15, borderRadius: 12, marginTop: 10, borderWidth: 1, borderColor: colors.border },
  label: { fontSize: 12, color: colors.textSecondary, marginBottom: 6, fontWeight: '600' },
  genderRow: { flexDirection: 'row', gap: 10, marginTop: 6 },
  genderBtn: { flex: 1, padding: 11, alignItems: 'center', backgroundColor: '#F8FAFC', borderRadius: 10, borderWidth: 1, borderColor: colors.border },
  activeGenderBtn: { backgroundColor: colors.primary + '22', borderColor: colors.primary, borderWidth: 1 },
});